typedef struct image_s {
    pixel_t *buf;
    int width;
    int height;
    bool has_alpha;
} image_t;

enum {
     RESOURCE_ICON_UNIOS = 0,
     RESOURCE_IMAGE_WALLPAPER,
     RESOURCE_IMAGE_TEST,
     RESOURCE_ICON_CURSOR,
     RESOURCE_IMAGE_LETTERS,
     RESOURCE_ICON_CALC,
     RESOURCE_CHAR_A,
     RESOURCE_CHAR_B,
     RESOURCE_CHAR_C,
     RESOURCE_CHAR_D,
     RESOURCE_CHAR_E,
     RESOURCE_CHAR_F,
     RESOURCE_CHAR_G,
     RESOURCE_CHAR_H,
     RESOURCE_CHAR_I,
     RESOURCE_CHAR_J,
     RESOURCE_CHAR_K,
     RESOURCE_CHAR_L,
     RESOURCE_CHAR_M,
     RESOURCE_CHAR_N,
     RESOURCE_CHAR_O,
     RESOURCE_CHAR_P,
     RESOURCE_CHAR_Q,
     RESOURCE_CHAR_R,
     RESOURCE_CHAR_S,
     RESOURCE_CHAR_T,
     RESOURCE_CHAR_U,
     RESOURCE_CHAR_V,
     RESOURCE_CHAR_W,
     RESOURCE_CHAR_X,
     RESOURCE_CHAR_Y,
     RESOURCE_CHAR_Z,
};
